version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - OUTLOOK_CLIENT_ID=${OUTLOOK_CLIENT_ID}
      - OUTLOOK_CLIENT_SECRET=${OUTLOOK_CLIENT_SECRET}
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"